steps:

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Build.ArtifactStagingDirectory)/symbols-Windows
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: ðŸ“¢ Publish symbols

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Build.ArtifactStagingDirectory)/test_symbols-Windows
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: ðŸ“¢ Publish test symbols

- powershell: azure-pipelines/Publish-Legacy-Symbols.ps1 -Path $(Build.ArtifactStagingDirectory)/symbols-Windows
  displayName: ðŸ“¢ Publish symbols for symbol archival
